version: "3.7"
services: 
  mysql-service:
    image: "mysql:5.5"
    container_name: myDb
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: amdfreitas
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: mercadoDB
    ports: 
       -  3306:3306  
    volumes:
        - "database:/var/lib/mysql"
    networks: 
       -  mysqlNode

  node_api:
    build: .
    container_name: apiTest
    ports:
      -  3000:3000
    networks:
      -  mysqlNode  

volumes:
  database:
    name: database

networks:
  mysqlNode:
    driver: bridge
   

    